title: luxianche's blog
description: "notes,passage,projects by luxianche"
author:
  name: "Lu Xianche"
  email: "luxianche9@gmail.com"
  url: "luxianche.tech"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "luxiache"
year : "2021"

intensedebate_comments: true
